### ISSUE TITLE
Delivery Item - Won't complete stages if ..

### ISSUE THREAD

**Issue by tara81** [Blackvein/Quests#297]
If the item to be delivered has light green in the item name, the stage won't complete after delivering it.

http://mc.pwing.net/wp-content/uploads/2016/03/2ndstage_pic_2.png

http://mc.pwing.net/wp-content/uploads/2016/03/2ndstage_pic_2.png

It took me a VERY long time to figure out it was light green causing the issue. :(

**Comment by FlyingPikachu** [comment]
I don't understand what you mean by light green causing the issue. Are you sure there is a stage set up after your delivery? If so, please post Quests version number and quests.yml file.

**Comment by tara81** [comment]
The lore name on an item , if the color is light green (&a) , then that item bugs out the quest and it won't give a reward.

I had to change all my quests that used light green color to different colors.

It took me all day.

  custom8:
    name: Magical Sword
    npc-giver-id: 937
    ask-message: §7Trade §a3 §6Crystal §5Shards §7and §a1 §aCommon §6Falchion §7for a §bMagical §6Claw ?
    finish-message: Ty
    stages:
      ordered:
        '1':
          items-to-deliver:
          - name-NETHER_STAR:amount-3:displayname-Crystal Shard:lore-§bP§3ower §4g§crows §dwithin.:lore-§6Used by powerful weaponsmiths.
          npc-delivery-ids:
          - 937
          delivery-messages:
          - Ty
          start-event: ExampleEvent
        '2':
          items-to-deliver:
          - name-MONSTER_EGGS:amount-1:data-2:displayname-§aC§2ommon §6F§ealchion §7of the §4M§cagma:lore-§c+12 Damage:lore-§e+1 Smite:lore-§8+1 Bane:lore-§4+100% ignition:lore-§3+1% Dodge:lore-The magma burns as it flows deeply:lore-within the blade.
          npc-delivery-ids:
          - 937
          delivery-messages:
          - ty
          start-event: ExampleEvent
    rewards:
      quest-points: 2
      commands:
      - loot give <player> magicalsword

**Comment by tara81** [comment]
To test it yourself, create a stage that requires an item named &aTest to be delivered to get the reward.

**Comment by tara81** [comment]
This issue is NOT in version 2.5.3. Nathan said he may have changed something with color codes.

**Comment by FlyingPikachu** [comment]
Would love to get input from @NathanWolf then. I couldn't find anything in his commits that would seemingly affect color codes.

**Comment by NathanWolf** [comment]
I did actually change something with color codes- I thought I had fixed some issues with saving colored items, particularly on systems with non-unicode encoding for the save file. Basically I just escaped/unescaped name and lore.

I've got a special build made for @tara81 that is up to date with my fork but does not include the two commits where I messed with color, currently waiting on the results of her testing that.

If that build works, I'll figure out what I broke and fix it- or failing that just revert my commits. I thought I was fixing something, but maybe I broke something unintentionally as well.

**Comment by tara81** [comment]
all i can say is if you use pikas 2.5.3 version, light green works fine .
Everything else appears broken.

**Comment by NathanWolf** [comment]
I guess that means my two color-related commits are not the culprit, but I'm not sure what else it'd be. It must be something I have in my fork, which I haven't synced to upstream in a while- meaning I think it has to be one of my changes somewhere. :\

**Comment by tara81** [comment]
damn I didn't think this would be such a hard fix.  I think its just not saving the color green properly.  The quests that used green item names in the past are still working, just cannot create new ones with the color green in the item name.

**Comment by FlyingPikachu** [comment]
#305 may be related

**Comment by tara81** [comment]
Version 2.5.5 introduced this bug. If you recreate your quest in version 2.5.3, green works.

**Comment by FlyingPikachu** [comment]
@tara81 I had no problem delivering this item on Quests 2.6.2 http://pastebin.com/k1muQ1Xx

**Comment by tara81** [comment]
well maybe it now reads the config properly.  try creating an item that is green for a quest in game ,.

**Comment by FlyingPikachu** [comment]
@tara81 I did just that in the pastebin I linked. Are you still experiencing this issue?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.

**Comment by tara81** [comment]
yes issue exists, i said this so many times
