### ISSUE TITLE
Custom objective permission issue

### ISSUE THREAD

**Issue by NouillOrc** [Blackvein/Quests#332]
Hi, english is not my native language, so i could make some typing mistake, sorry.
I'm running a spigot (1.9.2) server on 1.9 minecraft version, and today we try with a friend to install the mythicmob module for quest.
So, we made a special skeleton, and we made a quest which ask to kill this mob, let's call it "Bob".
When i try to do this objective being op, the objective completed well, but when i'm not, with a basic rank for example, killing the mob doesn't trigger the objective so the quest can't be complete.
We already look for specific permission which allow player to do these custom objective, but we found nothing except "mythicmobs.admin" and i don't really think we should give this permission to everyone.
We also look about quests permission for the mythicmob custom objective, same result, can someone help ? I already ask on the MythicMob forum and they tell me to ask here, thank.

**Comment by FlyingPikachu** [comment]
Please upload your Quests folder for testing. Make sure to point out which quest has the issue.

**Comment by FlyingPikachu** [comment]
Closing due to lack of responses from OP.
