### ISSUE TITLE
Console Spam on 2.6.1 

### ISSUE THREAD

**Issue by Liphius** [Blackvein/Quests#339]
Hi, i haven't had this console spam yet. Not sure what's causing it. I'm using 1.9.4 spigot with recent version of quests for 1.9.

> [?:?]
> 09.06 13:27:13 [Server] INFO at me.blackvein.quests.Quester.breakBlock(Quester.java:988) ~[?:?]
> 09.06 13:27:13 [Server] INFO Caused by: java.lang.NullPointerException
> 09.06 13:27:13 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:845) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:293) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:13 [Server] INFO org.bukkit.event.EventException
> 09.06 13:27:13 [Server] ERROR Could not pass event BlockBreakEvent to Quests v2.6.1-b100
> 09.06 13:27:12 [Server] INFO ... 17 more
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
> 09.06 13:27:12 [Server] INFO at me.blackvein.quests.PlayerListener.onBlockBreak(PlayerListener.java:495) ~[?:?]
> 09.06 13:27:12 [Server] INFO at me.blackvein.quests.Quester.breakBlock(Quester.java:988) ~[?:?]
> 09.06 13:27:12 [Server] INFO Caused by: java.lang.NullPointerException
> 09.06 13:27:12 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:845) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:219) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:293) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO org.bukkit.event.EventException
> 09.06 13:27:12 [Server] ERROR Could not pass event BlockBreakEvent to Quests v2.6.1-b100
> 09.06 13:27:12 [Server] INFO ... 17 more
> 09.06 13:27:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
> 09.06 13:27:12 [Server] INFO at me.blackvein.quests.PlayerListener.onBlockBreak(PlayerListener.java:495) ~[?:?]
> 09.06 13:27:12 [Server] INFO at me.blackvein.quests.Quester.breakBlock(Quester.java:988) ~[?:?]
> 09.06 13:27:12 [Server] INFO Caused by: java.lang.NullPointerException
> 09.06 13:27:12 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:10) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInBlockDig.a(SourceFile:40) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]
> 09.06 13:27:12 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:845) [Spigot194.jar:git-Spigot-8a048fe-5ff377a]

**Comment by FlyingPikachu** [comment]
Please upload your quests.yml for testing.

**Comment by Liphius** [comment]
http://pastebin.com/gQLTuWzm

**Comment by FlyingPikachu** [comment]
@Liphius I tested several of your quests and could not replicate the issue. However, I just noticed that several of your "npc-delivery-ids" in your quests.yml are duplicated. Backup your config, remove the duplicate entries and test the errors. For example:

          npc-delivery-ids:
         - 207
          - 207
          - 207

Should be

          npc-delivery-ids:
         - 207

AFTER you've tried that, if you're still getting errors, run this build of Quests which I've just exported for you. This will spit out additional information along with the error. Please reply back with the results. https://dl.dropboxusercontent.com/u/72509980/Quests-2.6.2-339.jar

**Comment by Liphius** [comment]
I deleted the multiple npc-delivery-ids and when I tried to reload the plugin (which was an issue before using the .jar you provided) it shows up with this error:

`[17:54:42 INFO]: Liphius issued server command: /questadmin reload
[17:54:42 ERROR]: [Quests] Stone Miner inside quests: Requirement for Quest Mob
Hunter is not a valid Quest name!
[17:54:42 ERROR]: [Quests] Make sure you are using the Quest name: value, and no
t the block name.
[17:54:42 ERROR]: [Quests] Stone Miner inside quests: Requirement for Quest Catc
h Fish is not a valid Quest name!
[17:54:42 ERROR]: [Quests] Make sure you are using the Quest name: value, and no
t the block name.
[17:54:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ques
tadmin' in plugin Quests v2.6.2-b${env.BUILD_NUMBER}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-8a048fe-5ff377a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot.jar:git-Spigot-8a048fe-5ff377a]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServe
r.java:646) ~[spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerCon
nection.java:1349) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:1184) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar
:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [spigot.jar:git-Spigot-8a048fe-5ff377a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
        at me.blackvein.quests.Quests.processStages(Quests.java:3718) ~[?:?]
        at me.blackvein.quests.Quests.loadQuests(Quests.java:2899) ~[?:?]
        at me.blackvein.quests.Quests.reloadQuests(Quests.java:2661) ~[?:?]
        at me.blackvein.quests.Quests.adminReload(Quests.java:884) ~[?:?]
        at me.blackvein.quests.Quests.questAdminCommandHandler(Quests.java:807)
~[?:?]
        at me.blackvein.quests.Quests.onCommand(Quests.java:788) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-8a048fe-5ff377a]
        ... 15 more`

**Comment by FlyingPikachu** [comment]
@Liphius Upload the new quests.yml?

**Comment by Liphius** [comment]
http://pastebin.com/UXuDPg9W

**Comment by FlyingPikachu** [comment]
Delete the default Mob Hunter and Catch Fish quests since you (apparently) deleted Stone Miner, which they both depend on as a requirement, then try again.

**Comment by Liphius** [comment]
Still an error when deleting that:

http://pastebin.com/hkdP36MZ 

Quests.yml: http://pastebin.com/Fu949bCT

**Comment by FlyingPikachu** [comment]
@Liphius Go ahead and use that build of Quests I linked to earlier, if you aren't already. What version of Citizens are you running?

**Comment by FlyingPikachu** [comment]
Personal note should OP ever respond:

`                    if (evt.getPlayer().getItemInHand().containsEnchantment(Enchantment.SILK_TOUCH) == false && evt.isCancelled() == false) {
                        
                    	//TODO remove
                    	System.out.println("Debug data for issue #339 - copy everything below this line including errors");
                    	System.out.println("Player name: " + evt.getPlayer().getName());
                    	System.out.println("ItemInHand: " + evt.getPlayer().getItemInHand());
                    	System.out.println("Quest: " + quest.name);
                    	System.out.println("Quest desc: " + quest.description);
                    	System.out.println(evt.getBlock().getType());
                    	            	                    	
                    	quester.breakBlock(quest, evt.getBlock().getType());
                    }`

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
