### ISSUE TITLE
Quests Issues

### ISSUE THREAD

**Issue by Kizuuna** [Blackvein/Quests#354]
I just made a github account to ask this question so this may be in the wrong spot.

Long messages:
If I were to edit quest messages in the config, could I make them indefinitely long? Since I would like to add backstory and depth to the quests players will take, but I can't do that with the minecraft chat which can barely fit a decent question. Is there anyway to make longer messages?

Boss fights:
I have a lot of bosses which takes parties of players to defeat, but only 1 player can finish the quest at a time since they need to kill the boss. Is there anyway to add an objective like Damage Mob until Death. So the player needs to damage the mob, and the quest is completed when the mob dies whether you or someone else kills it.

SkillAPI module:
Everytime I download Quests in the modules folder there's always a skillapi module. I do have skillapi installed, but I can not find any information on it. What exactly can I do with this?

Options support:
Item options such as repairable, damage values, knockback resistance, followrange, etc can not be item rewards. When you get the reward all of it's options will be gone. Can support be added for this?

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from community. If these questions are pertinent, try the Spigot forums?
