### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by saladfingers** [Blackvein/Quests#365]
Quests version 2.6.5-b104
spigot version: git-Spigot-a9631d2-56813c7 (MC: 1.10.2)

I'm seeing the following error repeatedly in the console:
http://pastebin.com/SCEHQvUv

**Comment by Volkenstein666** [comment]
Im no expert - but are you using an updated version of citizens as well? Quests really demands everything be current- that means latest spigot buildtools version, latest citizens, latest Quests, latest Sentinel .jar (Sentry has been abandoned and has become Sentinels), and possible the latest Protocollib .jar

**Comment by Blackvein** [comment]
You will need to provide steps to reproduce this problem, as well as your Quests config. Without that we can't diagnose the problem.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
