### ISSUE TITLE
How to Use "Gui Display" With Citizens?

### ISSUE THREAD

**Issue by iskillzi** [Blackvein/Quests#372]
Can't figure out how to use this gui display mentioned on the plugin page, how do I set it up?

Edit: by set it up I mean get quests to show up in the gui, since that probably wasn't a clear question from above.

**Comment by Volkenstein666** [comment]
I can field this one...
1) target the npc you want to display gui by standing near them and typing /npc select
2) get the npc's id number by typing /npc id
3) do /questadmin togglegui <npc id number here NO BRACKETS>

done- that should work

**Comment by Blackvein** [comment]
Volkenstein is correct. Toggle the GUI using the command with a specific NPC ID. When you do that, any Quests that have been assigned to that NPC will now show up in an inventory display when you right-click on that NPC.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP
