### ISSUE TITLE
Quester not found for UUID blah blah consider adding them to the Quester blacklist...

### ISSUE THREAD

**Issue by Volkenstein666** [Blackvein/Quests#373]
What is causing this console spam? I have noticed a curious thing about the UUID's that get thrown in the error spam. When I copy / paste the UUID's and try to locate them in my Citizens2 saves - I get a match on an NPC for MOST of the UUID but it is not an exact match. For example...

Here is a UUID that gets thrown in the console spam for an NPC
7b90004c-37d3-2280-b269-d7d068fc5c8e

Here is the closest match for that UUID as found in my Citizens2 saves. It applies to an npc that DOES hold a quest
7b90004c-37d3-**4**280-b269-d7d068fc5c8e

as you can see it is nearly an exact match except for the one number in the UUID that I have put in bold type

I can only assume this is the npc causing the problem. Weird huh?

**Comment by Volkenstein666** [comment]
If there is a simple fix for this (such as adding the particular UUID thrown in the error spam to the Quester blacklist) I will gladly do it and be done with it. But I dont know where the Quester blacklist is...

**Comment by jjm223** [comment]
The blacklist is located in the config file. You can add or remove names there. However, I also am experiencing the console spam that you mention, and I'm not sure if I've configured something improperly or not.

**Comment by Volkenstein666** [comment]
I actually found it after posting this yesterday and put both UUID's in the blacklist that were throwing errors in the condole. When I tried to run /questadmin reload some time after doing this it said that I had been blacklisted. Spooky stuff... my UUID is nowhere near what I put in the blacklist

**Comment by Blackvein** [comment]
I'll give you some insight here. So basically the point of the blacklist is this: Occasionally servers have certain entities that are considered "players". This is especially common in modpack servers. The trouble is Quests can't differentiate between these entities and actual players, so it gets confused and problems happen.

The blacklist exists so you can tell Quests to basically "ignore entities with this ID. They aren't players."

Hopefully that clears it up.

**Comment by jjm223** [comment]
@Blackvein Would players created using Citizens need to be blacklisted?

**Comment by Blackvein** [comment]
@jjm223 I'm not sure what you mean by "players created by Citizens" but if the entity type is Player then yes they should be added to the blacklist.

**Comment by jjm223** [comment]
@Blackvein I'm referring to the player NPCs that can be created with Citizens. I haven't had an issue with them in the past, but in any case, the UUIDs that were shown in the console were real players when I looked them up. This happened two versions ago, so perhaps it was fixed.

**Comment by Blackvein** [comment]
@jjm223 If it's just a standard Citizens NPC (that looks like a player) then it's fine. Quests checks if the 'Player' entity is a Citizens NPC before it treats it as an actual player.

**Comment by Volkenstein666** [comment]
First of all hello Blackvein. I love your plugin and many thanks to you, Pikachu, and the others who have kept it up to date. It is an incredible boon to server owners who want to add some sorely needed life to their servers and a great utilization of Citizens2 (another brilliant plugin). Your work is appreciated. If you read the initial post I made it appears that the UUID's that get thrown in my console error spam are **one character off** of a UUID that applies to an actual quest holding NPC as found in my Citizens2 save file. Yet when I post the 2 UUID's that get thrown in the error spam into my Quester blacklist - **I** get blacklisted. This is admittedly a minor issue, but  I like to play detective sometimes and I'm trying to get to the bottom of it. I have read the above conversation and I understand what youre getting at. The problem is the UUID's that get thrown dont seem to be an exact match of ANY Citizens2 created NPC. Nor do they apply to me and since Ive completely cleaned my server of any other users it cannot apply to a player. Nor would I think they apply to another  player since they so closely correspond to a Citizens2 created NPC. The server I run is admittedly old with alot of baggage attached to it. Do you have any ideas where I might be able to locate the UUID's in question any other place in my server folder at all? Or where would it make sense to start looking for them?

**Comment by Volkenstein666** [comment]
UPDATE! I have found a workaround for the issue- by going into my Citizens2 save file and altering the UUID of the suspected NPC's to match the UUID of the error spam that closely resembles that NPC it has stopped the error text from being thrown. Still don't know what would cause Quests to misread the UUID of an NPC in Citizens though, but oh well good enough problem solved :)

**Comment by FlyingPikachu** [comment]
Have not heard of this problem persisting in recent builds. However, if this is still a problem, please open a new ticket referencing this one. Thanks!
