### ISSUE TITLE
Quest with time bug

### ISSUE THREAD

**Issue by TerZer** [Blackvein/Quests#376]
When I finish quest, check time of quest and relog, it will let me start quest without cooldown.

**Comment by FlyingPikachu** [comment]
Duplicate of #317

**Comment by FlyingPikachu** [comment]
Re-opening because OP of #317 is unresponsive.

@TerZer Please upload your quests folder for testing. Thanks!

**Comment by TerZer** [comment]
That's the bug: http://imgur.com/XXlFsQu
Folder: http://www105.zippyshare.com/v/400g5USh/file.html

**Comment by FlyingPikachu** [comment]
@TerZer Could you please point out which quest you used for testing? I appreciate the video, but it is difficult to tell.

**Comment by TerZer** [comment]
That quest called: Pagalba

**Comment by dadee971** [comment]
Same issue:

I have a redo-delay prob.
Players just have to disconnect and reconnect and they can redo the quest without any delay.

CraftBukkit version git-Spigot-078e2f8-21e3b05 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Quest 2.6.8.

**Comment by Legendaryx** [comment]
I have the same issue. Is this being fixed or anything ?

**Comment by FlyingPikachu** [comment]
Fixed in #535
