### ISSUE TITLE
Could not pass PlayerJoinEvent + PlayerMove

### ISSUE THREAD

**Issue by Tristag** [Blackvein/Quests#377]
http://hastebin.com/iqobugequy.avrasm

Not sure what causes it, sometimes it happens when players join and other times it doesn't.

**Comment by FlyingPikachu** [comment]
While you did post first, issue #380 is using the current version (whereas you are using Quests 2.6.1), so we will proceed from his error. If you would like to contribute, update to the latest version of Quests and post your "new" error in #380. Thanks!
