### ISSUE TITLE
Bug: Can't select an NPC 

### ISSUE THREAD

**Issue by Sprungente** [Blackvein/Quests#383]
I would create a new quest and i got the queststart to an npc. When I insert the npcnumber nothing is happen. I tried it multiple times.

The Error:

17.07 12:15:43 [Server] ERROR Error handling conversation prompt
17.07 12:15:43 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang/math/NumberUtils
17.07 12:15:43 [Server] INFO at org.bukkit.conversations.NumericPrompt.isInputValid(NumericPrompt.java:16) ~[spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at org.bukkit.conversations.ValidatingPrompt.acceptInput(ValidatingPrompt.java:25) ~[spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:58) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1044) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1200) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.util.Waitable.run(Waitable.java:24) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:742) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot1100.jar:git-Spigot-078e2f8-7f9fbe5]
17.07 12:15:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by FlyingPikachu** [comment]
This is not an issue with Quests. Please report this to Spigot. Thanks!
