### ISSUE TITLE
Redo Delay Not working.

### ISSUE THREAD

**Issue by dadee971** [Blackvein/Quests#387]
Hi,

I have a redo-delay prob.
Players just have to disconnect and reconnect and they can redo the quest without any delay.

CraftBukkit version git-Spigot-078e2f8-21e3b05 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Quest 2.6.8.

**Comment by FlyingPikachu** [comment]
Duplicate of #376

**Comment by dadee971** [comment]
Right but their are no solutions in #376

**Comment by FlyingPikachu** [comment]
@dadee971 The is no reason to have a duplicate issue. Feel free to contribute in the ticket currently being worked on.
