### ISSUE TITLE
QUESTION/HELP: More than one quest

### ISSUE THREAD

**Issue by ChickenPillow** [Blackvein/Quests#390]
Hello, so I'm making an adventure/survival server and want to add quests (this plugin :D) But what I want to do is this:

Say there is a miner. You click on him and he says, like go and get 1 gold. You get gold and then go back to him, click on him and get a reward (say $500) and then if u click on him again he says something like, go and get 1 diamond. Then u go back on click on him and get a reward (say $1000)

And then it basically carries on, giving quests one after another, after completing the one before.
Etc.

Is this possible (and if so how?)

Thanks

**Comment by LeafyMitsuwa** [comment]
Hello ChickenPillow,

Wanting to create something similar to yourself, I can say that you can use NPC's as targets for your players to interact with; however, you will need the Citizens 2 plugin.

That having been said, it is possible to chain quests, or even chain events in a single quests.

I'd recommend you watch the admin tutorial: https://www.youtube.com/watch?v=0EZ6yv4MVBM -- which is the same one documented on the frontpage of the Spigot resource page.

As for how, use the ingame quest editor this plugin provides, which can be accessed with '/quests editor'

**Comment by FlyingPikachu** [comment]
@ChickenPillow Like @LeafyMitsuwa said, use multiple stages or create several quests that should be taken in order (you could enforce this with Quest points).
