### ISSUE TITLE
Question: Variables

### ISSUE THREAD

**Issue by LeafyMitsuwa** [Blackvein/Quests#391]
This question seems somewhat related to issue #36, in the sense of using commands to reward players.

Quests version: 2.6.8

What I'd like to do, is run commands, be it to set permissions via PEX or give items directly to players, my question being is that I have read through the documentation, however, any variable seems to be lacking.

Small edit: I am aware I can set permissions via the permissions tag, this is working perfectly fine; I'd like to use commands to remove said permissions in order to chain quests.

All that I've managed to find is: '(You may put "" to refer to the player who completed the Quest. Leave slashes out.)'.

This does not make much sense to me, syntax-wise. I've tried experimenting with several formula, but no success thus-far.

So, my question being, how would I use a single permission command reward to generate, say, an apple to anyone who completes quest x.

So far, my experiments have resulted in no success.
Some examples tried.

- give "" 260 1
- give "%player%" 260 1
- give "%playername%" 260 1
- give "%user%" 260 1
- give "%username%" 260 1

Sincerely,
LeafyMitsuwa

**Comment by FlyingPikachu** [comment]
I'm sure someone can shed some light on this, however wouldn't it be easier to just give the player an Apple as a stage reward?

**Comment by LeafyMitsuwa** [comment]
If it would be an plain, vanilla apple, then yes, then I could consider using programming an item reward with an apple; however, this is not the case -- merely having used an apple as an example.

I was planning initially to use permissions as quests flags, removing prior flags via commands; however the quests Quest requirements would not be what I wanted, but it would give me what I need, so that's that.

In the meanwhile, the initial question still stands for variables used mapped; most specifically player name completing a quest (stage), regardless of context.

**Comment by LeafyMitsuwa** [comment]
The answer was given to me in issue #385, which turns out the variable for player is "<player>", quotation marks not included.

Consider updating the wiki, as editing the wiki reveals <player> documented, however this gets removed in the output, probably thinking it is an HTML tag.
