### ISSUE TITLE
Block ID's

### ISSUE THREAD

**Issue by Soup33113** [Blackvein/Quests#395]
Is there a way to make it recognize granite or am I just missing it?  When doing block break quests it says granite is a invalid name.  Also when using 1:1 it says it's not a valid name.  Am I doing something wrong or is this something you can update?

**Comment by FlyingPikachu** [comment]
@Soup33113 Post your Quests version.

Possible duplicate of #381

**Comment by Soup33113** [comment]
2.6.8

**Comment by FlyingPikachu** [comment]
@Soup33113 Only the latest dev build (2.7.0) supports block durability, and only for block-break at the moment. Give it a try! :)

http://ci.ac3-servers.eu/job/Quests/111/
