### ISSUE TITLE
Duplication of quest tasks

### ISSUE THREAD

**Issue by Soup33113** [Blackvein/Quests#401]
I am attempting to make a quest that is using  the block durabilty and am getting a duplication of the items to break. Version 2.7.0

![](https://i.gyazo.com/e1b1556c4130c8f8c077d1e0ca72ce60.png)

![](https://i.gyazo.com/bea88e6299891eda37d0b7b5d5a19b71.png)

**Comment by FlyingPikachu** [comment]
@Soup33113 Please post your quest config as text (not an image) as that will help facilitate the process.

**Comment by Soup33113** [comment]
quests:
  Miner25:
    name: Miner 25
    npc-giver-id: 1
    redo-delay: 172800
    ask-message: <yellow>Collect <blue>25 <darkgreen>Granite<yellow>, <darkgreen>Diorite <yellow>and <darkgreen>Andesite<yellow>.
    finish-message: Good job
    gui-display: name-Stone:amount-1
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - Stone
          - stone
          break-block-amounts:
          - 25
          - 25
          - 25
          break-block-durability:
          - 1
          - 3
          - 5
          items-to-deliver:
          - name-STONE:amount-25:data-1
          - name-STONE:amount-25:data-3
          - name-STONE:amount-25:data-5
          npc-delivery-ids:
          - 1
          - 1
          - 1
          delivery-messages:
          - Thank you
    rewards:
      money: 10
      quest-points: 1

**Comment by Soup33113** [comment]
quests:
  Miner25:
    name: Miner 25
    npc-giver-id: 1
    redo-delay: 172800
    ask-message: <yellow>Collect <blue>25 <darkgreen>Granite<yellow>, <darkgreen>Diorite <yellow>and <darkgreen>Andesite<yellow>.
    finish-message: Good job
    gui-display: name-Stone:amount-1
    stages:
      ordered:
        '1':
          break-block-names:
          - STONE
          - Stone
          - stone
          break-block-amounts:
          - 25
          - 25
          - 25
          break-block-durability:
          - 1
          - 3
          - 5
          items-to-deliver:
          - name-STONE:amount-25:data-1
          - name-STONE:amount-25:data-3
          - name-STONE:amount-25:data-5
          npc-delivery-ids:
          - 1
          - 1
          - 1
          delivery-messages:
          - Thank you
    rewards:
      money: 10
      quest-points: 1

**Comment by Soup33113** [comment]
Since that didn't work.
[http://pastebin.com/GXKP2xAU](http://pastebin.com/GXKP2xAU)

**Comment by FlyingPikachu** [comment]
@Soup33113 Fix will be applied in the dev build below once available. Thanks for supporting Quests!

http://ci.ac3-servers.eu/job/Quests/114/
