### ISSUE TITLE
Can't use blocks with meta IDs for block breaks

### ISSUE THREAD

**Issue by JoltNetwork** [Blackvein/Quests#403]
Hello Pikachu/Blackvein

I'm having issues selecting blocks like 17:1 as block break in quest stages. Meta ID blocks only seem to work with deliever. Is this an error or am I doing it wrong?

Please help, it really keeps me from doing a lot of quests.

Best regards
Naskel

**Comment by Soup33113** [comment]
I had this same issue.  Minecraft doesn't use the numerical ID anymore.  That being said you'll want to do something like this
break-block-names:
- log
break-block-amounts;
- 0
break-block-durability:
- 1
The break-block-durability is the numerical id for the block, also make sure you are using ver 2.7.0 or above.

**Comment by FlyingPikachu** [comment]
Update to the latest dev build to use block durability. Block IDs are not supported.

**Comment by JoltNetwork** [comment]
So I will never be able to use blocks like Spruce logs or Andesite blocks in the quests?

**Comment by FlyingPikachu** [comment]
@JoltNetwork You can via the latest dev build. Use the block name and durability number. The documentation for this will be updated once the build makes its release on Spigot.

**Comment by JoltNetwork** [comment]
Sorry but I don't think I understand. How is durability connected to the block type?
When making the quest with the ingame editor. If I type Log:1 or Wood:1 or 17:1 or 5:1 or Spruce_Wood or SpruceWood - Nothing works.

Could you please tell me how?

**Comment by JoltNetwork** [comment]
Ah. I finally figured it out. Sadly though - It doesn't let me add multiple blocks of the same value. 
Meaning I can't have a lumberjack quest where they have to chop down both oak logs and spruce logs since they share the same ID.

Can this option be fixed/added? :)

**Comment by FlyingPikachu** [comment]
@Naskel-CastiaMC Please update to the latest dev build. If that doesn't resolve the issue, open a new ticket describing your problem. Make sure to include the steps you took. Thanks!
