### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by Naskel-CastiaMC** [Blackvein/Quests#404]
While making a lumberjack quest using the latest quests version (2.7.2 Build 114), I discovered the following bugs.

1. There is no longer any "Destroy blocks" in stages using the quests editor

2. In the quests editor, it doesn't let me add multiple blocks of the same value. 
Meaning I can't have a lumberjack quest where they have to chop down both oak logs and spruce logs since they share the same ID. Can this option be fixed/added?

3. In the Cut blocks stage, it duplicates. As shown here http://prntscr.com/c7dmbr

Best Regards
Naskel

**Comment by FlyingPikachu** [comment]
1. I have never seen "destroy blocks". Do you mean "break blocks"? If so, provide a picture.

2. This has been noted in #403 and will be dealt with soon

3. Is this only in the Quests Journal or does it duplicate in chat as well? Can you provide a quest config to test with?

**Comment by Naskel-CastiaMC** [comment]
1. Oh yeah, I meant break blocks. This is the exact same quest but using the quests editor in different versions 2.6.8 http://prntscr.com/c7gaco 2.7.2 http://prntscr.com/c7g9h3 Notice in 2.7.2 the 1 is Place blocks, but it's also the same under 3.

2. Great news, I really hope to have it added soon. I'm dying to get some job quests added to my server! :smile: 

3. I'm not sure how to the "cut blocks" work, even if I break blocks it doesn't count it so I can only see it duplicate in the quests journal. Either way, here is a copy of the config http://hastebin.com/umeficixan.sm

Another little note. If you notice in the 2.7.2 screenshot of the quests editor. Notice the cut blocks say Log x 0 but as shown in my previous screenshot, the journal says x 64

**Comment by FlyingPikachu** [comment]
@Naskel-CastiaMC Parts 1 and 3 should be fixed with the latest development version. Kindly give it a try and if part 2 is still desired, open a new issue for that. Thanks!
