### ISSUE TITLE
Ask messages

### ISSUE THREAD

**Issue by smiggle0404** [Blackvein/Quests#408]
There's a bug where when you input an ask or finish message, It won't return the player name.
For example "Hi there < player >, can you help me?" 
It will just repeat that into the GUI menu...i've tried <player_name>and placeholders from the placeholderAPI like %player_name% but none are working...i'm guessing this would be a critical issue for permission rewards if a reward was to be something like /pex user < player > add my.permission.node

edit: had to put spaces between <> and player or it disappears on github only

**Comment by FlyingPikachu** [comment]
Closing as OP has apparently resolved issue (see edit).
