### ISSUE TITLE
Placed jar into plugin folder and did full restart but not loading

### ISSUE THREAD

**Issue by rampage211** [Blackvein/Quests#414]
I have Vault and Citizens2

Attatched image with list of plugins

![plugins](https://cloud.githubusercontent.com/assets/21981051/18229270/3897846e-7238-11e6-9c6e-4725c821e0f3.png)

Console
04.09 01:53:26 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
04.09 01:53:26 [Server] ERROR Could not load 'plugins/Quests-2.7.3.jar' in folder 'plugins'

Did a little browsing on the error and it seems that the file I downloaded possible does not have a plugin.yml in it or it may be misspelled, after attempting to re-download the jar same error presisted.

further I found that this is not client side and has something to do with the bukkit or possibly I am missing a plugin "node" or another plugin that is required to unpack the quest-2.7.3.jar?

Further help will be needed from the author, I would prefer not to enter an editor and atempt fixing it myself since this probably is occurring for other players.

Regards:
-rampage211

**Comment by BloodSKreaper** [comment]
Hey there:
Whats the Download link of your version? 

With kind regards
BloodSKreaper

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.

**Comment by ApolluZed** [comment]
I have the same problem, and these are the plugins I have:

![image](https://cloud.githubusercontent.com/assets/17578698/25309180/f94b8dac-2793-11e7-9813-254f0fbb9c0d.png)
