### ISSUE TITLE
[Question] Level based on xp gained

### ISSUE THREAD

**Issue by DrRek** [Blackvein/Quests#415]
Hi, i was trying to find a way to add levels based on xp gained via quests. I was thinking about using PermissionEx but i don't know how to add a player to a "pex group level" if they have more than some xp.

For examples:
i'm level 1, to reache level 2 i need 100 xp. There are 3 quests that i can do that can gives me 50xp.
I need to find a way to control at the end of every quests if my xp is more that 100 execute command "pex user me add group level-2"

Thanks for your time.

**Comment by FlyingPikachu** [comment]
Afaik this is not something Quests is currently capable of doing. Unforunately, no features are being added by myself at this time, so you might want to look into having another plugin handle this for you. Thanks for your interest in Quests!
