### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by AndresBlitz** [Blackvein/Quests#420]
I keep getting a null everytime i do /quests  everything says null and its bugging me out idk what to do hi
![here](https://cloud.githubusercontent.com/assets/22250963/18605821/c63bc18a-7c6b-11e6-9136-d30f5b9099d3.png)

**Comment by Psychlist1972** [comment]
I have the same issue. Updated to latest vault as well. Still no change.

**Comment by FlyingPikachu** [comment]
Try updating to the latest version of Quests from Spigot and create a new issue if this problem still persists.
