### ISSUE TITLE
Level condition + Skillapi Bug

### ISSUE THREAD

**Issue by iSiiLeX** [Blackvein/Quests#423]
Heyho,

 **Bug description:**
 If I accept a Quest with my Lv. 60 Account and change to a new Account (Lv. 1) and finish the Quest then the Lv. 1 Account will get the Exp for the Quest.
 The Lv. 60 Quest can normaly only accepted if the Player is Lv. 60. (Quest Condition)
_This Way Players could Level insanly fast._

**What can fix it**
The Bug could be fixed if every Skillapi Account gets his own Quests.
So that the Players can do the Same Quest with all 5 Accounts for example.

**Comment by FlyingPikachu** [comment]
@iSiiLeX Provide an example quests.yml, keeping in mind Quests does not formally support SkillAPI

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
