### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dafafdd** [Blackvein/Quests#424]
Hi, is there any version of Quests which is compatible with Tekkit Lite (1.4.7)? I´m searching a plugin who doesn´t spam my console with issues.
Also it should contain, by completing the quest, to execute a command.
Hope you can help me :)

//edit: Do i need Citizens for Quests? Because i tried it with a older version without it and it spams my console.

Greetz

dafafdd

**Comment by ValarDragon** [comment]
I sincerely doubt any of the developers would know off-hand whether Quests would / wouldn't be supported by Tekkit Lite, or would be willing to test every version. Assuming you run linux, building and checking multiple versions should be trivial through git. This something I would assume that you need to test.


For your second question, read the plugin.yml
https://github.com/Blackvein/Quests/blob/master/src/main/resources/plugin.yml
It only softdepends on citizens, so it doesn't need it. It needs vault.

Note, I am not associated at all with developing quests.

**Comment by dafafdd** [comment]
Hi, i found a version which works fine with Tekkit Lite and Citizens 2 (The Quests 1.5.4b Beta).
But now i got an another question, how can i make that an NPC can offer an player 2 or more quests?
It only works with one quests and if i wanna put the another quest on the NPC and then it says you already completed quest1.

Help Please :D

**Comment by FlyingPikachu** [comment]
Sorry, Tekkit is not officially supported and no support is planned. Thanks for your interest in Quests!
