### ISSUE TITLE
Mythicmobs Mobs?

### ISSUE THREAD

**Issue by odbro99** [Blackvein/Quests#427]
So im using mythicmobs with quest and i have a little issue... My mobs are "BABY-ZOMBIE" but are disguised to other mobs as chicken, cow you name it. But in order for it to work i have to put in "BABY-ZOMBIE" as the required mob kill for completeing the quest. Wich makes my players a little confusing as they are told to kill "Super Chickens" but it says it needs 20x Baby Zombie kills. How can i change that?

Best Regards,
Odbro99

**Comment by FlyingPikachu** [comment]
Please speak to the developers of the MythicMobs module regarding this issue.
