### ISSUE TITLE
Mythicmobs kill Bug

### ISSUE THREAD

**Issue by iSiiLeX** [Blackvein/Quests#431]
Some Mythic Mobs dont count  if a Player kills them but only on some Quests.
Below there are 2 Quests. The First does not work, the second does.
## **Does not work**

  custom2:
    name: Töte 10 Hühner für Paldrin
    npc-giver-id: 468
    ask-message: AHHHHHH HÜHNER!! ÜBERALL HÜHNER!! Meine schönen KÜRBISSE!!!
    finish-message: Danke für deine Hilfe. Ich habe panische Angst vor Hühnern. Nimm diese Belohnung.
    gui-display: name-EGG:amount-1
    requirements:
      quests:
      - Paldrins Albtraum
      fail-requirement-message: Besorg dir erst eine Waffe bei Laemtao
    stages:
      ordered:
        '1':
          **custom-objectives:
            custom1:
              name: Kill MythicMobs
              count: 10
              data:
                Killable Types: kether1,kether2
                Objective Name: Kleines Huhn
          start-message: Töte 10 Hühner**
        '2':
          npc-ids-to-talk-to:
          - 468
    rewards:
      money: 300
      quest-points: 1
      custom-rewards:
        req1:
          name: Class Experience Reward
          data:
            Experience: '200'
## **Does work**

  custom47:
    name: Schamanen der Nagas
    npc-giver-id: 653
    redo-delay: 1
    ask-message: Töte 20 Schamanen der Nagas.
    finish-message: super. Aber wo die herkommen gibt es noch mehr.
    gui-display: name-DIAMOND_AXE:amount-1
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs
              count: 20
              data:
                Killable Types: lirelia7
                Objective Name: Schamanen
          complete-message: Zurück zu Dewey
        '2':
          npc-ids-to-talk-to:
          - 653
    rewards:
      money: 1000
      custom-rewards:
        req1:
          name: Class Experience Reward
          data:
            Experience: '4500'
  custom32:
    name: Schreckliche Sumpfmonster!
    npc-giver-id: 620
    redo-delay: 600
    ask-message: Ich brauche dringend deine hilfe! Bitte töte diese wiederlichen Sumpfmonster damit ich hier in Ruhe spatzieren gehen kann!
    finish-message: Danke, endlich ist es hier etwas sicherer.
    gui-display: name-WATER_LILY:amount-1
    requirements:
      custom-requirements:
        req1:
          name: Class Level Requirement
          data:
            Group: class
            Level: '20'
      fail-requirement-message: Du musst mindestens level 20 Erreicht haben, um diese Quest anzunehmen.
    stages:
      ordered:
        '1':
          **custom-objectives:
            custom1:
              name: Kill MythicMobs
              count: 12
              data:
                Killable Types: moorhain3
                Objective Name: Töte [Lv.23] Sumpfmonster
          complete-message: Das waren alle, erstatte Lenera Bericht.**
        '2':
          npc-ids-to-talk-to:
          - 620
    rewards:
      exp: 5
      custom-rewards:
        req1:
          name: Class Experience Reward
          data:
            Experience: '6500'

**Comment by FlyingPikachu** [comment]
Please speak to the developers of the MythicMobs module regarding this issue.
