### ISSUE TITLE
Add "any durability"

### ISSUE THREAD

**Issue by Vynderman** [Blackvein/Quests#433]
If I want to give players quest "Break bed" I cannot do it normally. Because durability=0 it is just one angle of bed (For example, bed:0 = west, bed:1 = north, etc). Also, If I want to allow players set any wood to complete quest (like wood:0 wood:1 wood:2, etc) I cannot do it too (Only wood:0 or wood:1, etc).

I want to see something like that:

```
place-item-durability:
  - any
```

**Comment by FlyingPikachu** [comment]
Iirc you can just not include a durability. If I'm wrong feel free to create a new issue. Thanks!
