### ISSUE TITLE
Quests problem - Bugs after reloging

### ISSUE THREAD

**Issue by RejcatkoCZ** [Blackvein/Quests#441]
Hello,
my problem with plugin is quite weird. We have Quests on a pvp server, where are ca 20 players per a day.
Problem is, that player has an active quest, for example "Kill 10 zombies". Just example. If player won't finish this quest before he will log out, after reloging in game is the quest very weirdly bugged. Player can't continue making this quest, or the quest is deleted from player's actives quests, or if there is more than one thing in objective, the values can switch between themselves and the quest becomes not possible to finish. It seems to happen kinda random and the console has no vissible errors about Quests. Can you give me some advice or tell me what could be wrong? And if there is any information you need to help me, just let me know.
Tahnks and best Regards
RejcatkoCZ

**Comment by LeZalox** [comment]
Bump, we still have these problems.

**Comment by FlyingPikachu** [comment]
Possibly fixed in latest pull request. Would need to see this bug replicated on newer builds anyway, so I'm closing this. Please make a new issue if this still persists. Thanks!
