### ISSUE TITLE
what is happening with data files

### ISSUE THREAD

**Issue by SliderKP** [Blackvein/Quests#443]
years used this plugin, recently I turned to use it, but I have problems of my users lose their process, and have to start from 0 to missions, perhaps implementing sql solve this? I'm using 2.6.8 on my server 1.8.8, as the 2.7.3 get errors, I hope your answer and help!

**Comment by FlyingPikachu** [comment]
https://github.com/Blackvein/Quests/wiki/Updating-from-2.0.0
