### ISSUE TITLE
Quester not found error in consol

### ISSUE THREAD

**Issue by jdk789** [Blackvein/Quests#444]
Hey,

So today I found that the following error is being spammed in the consol
Quester not found for player "5b5689b9-e43d-4282-a42a-dc916f3616b7". Consider adding them to the Quester blacklist.

I added this to the blacklist but it did not stop this error. I can't even find that player in my player data its like it is looking for it but it doesnt exist.

Please advise.

Jay.

**Comment by Volkenstein666** [comment]
hey jdk check out this link - its a bit of a long read but I found a workaround solution for that

https://github.com/Blackvein/Quests/issues/373

**Comment by MeSoLost** [comment]
i fixed this error by making a copy of my players blank quester info file and renaming it from my UUID to the UUID of the fake player

**Comment by FlyingPikachu** [comment]
Duplicate of #373
