### ISSUE TITLE
Quests needed to complete

### ISSUE THREAD

**Issue by Ashstyx** [Blackvein/Quests#455]
Hello, i have a quest that i would like to give people but they would have to have completed another quest before hand, this screen shot shows that it thinks i have not done the quest but as a matter of fact i have completed the quest, im running 1.10 server craftbukkit

https://gyazo.com/0fb03fecc069f3478b3522125c2d49aa

**Comment by FlyingPikachu** [comment]
Likely fixed in latest merge.
