### ISSUE TITLE
Wiki not up to date

### ISSUE THREAD

**Issue by darkthomate** [Blackvein/Quests#461]
As said in the title, various entry in the wiki are not up to date. Therefore, creating a quest is empirical.

**Comment by FlyingPikachu** [comment]
@darkthomate Assuming you mean the official wiki in this repo, which entries are outdated? Details, please.

**Comment by darkthomate** [comment]
For example, in Configuration>quests.yml->Stages, damage-block-durability is not mentioned.
After the update of our Quests plugin, we saw multiple error "damage-block-durability is missing" and had to do some trial and error to figured out how to use it.

**Comment by FlyingPikachu** [comment]
Wiki entry has been updated to explain durability. Thanks!
