### ISSUE TITLE
Scoreboard use for for specific quests

### ISSUE THREAD

**Issue by Enoceant** [Blackvein/Quests#465]
I would like a feature where you can show the stage you are currently on and what you have to do in that stage like this, that updates as well.

Stage 1
Kill 15 Zombies > Kill 14 Zombies

Stage 2
Kill Boss

Congratulations
(After finishing the quest)

That is how I would like the format
I would like this feature because in my rog server there are dungeons, and I don't want them to keep lookin in their journal all the time.

But i also like the journal for normal quests
So can you add this so you have to specify if you want to use the scoreboard or not for this quest.
In the Quest editor

Also add an alias for /quests journal to /j /journal

**Comment by Enoceant** [comment]
Bump

**Comment by bingoberra** [comment]
Can't this be made with vanilla scoreboard and events? :o

**Comment by FlyingPikachu** [comment]
@bingoberra You're correct. Either way, Quests is not in any condition for enhancements at this time.

Closing due to lack of response from OP.
