### ISSUE TITLE
Quests do not retain their proper GUI icon

### ISSUE THREAD

**Issue by Neoblade298** [Blackvein/Quests#470]
When editing a quest, if I formerly had the quest icon to be, say, 5 diamonds, after saving the quest it'll be reverted to 1 diamond. The only way to set icons that have amounts greater than 1 is to manually go into quests.yml.

The editor also shows that the GUI has amount 5 even though it ends up being 1.

**Comment by FlyingPikachu** [comment]
I'm unsure whether this is an oversight or if Blackvein intended for GUI items to not show numerical amounts. Although I'm curious why you would want them too, I'm closing this as there doesn't seem to much interest in adding/fixing this functionality atm. Perhaps it can be resubmitted as an enhancement in the future. Thanks!
