### ISSUE TITLE
Feature Request - Integration with nuNPCDesintations

### ISSUE THREAD

**Issue by Arctomium** [Blackvein/Quests#474]
Hey thought this would be a good feature to have because I'm currently using [nuNPCDesintations](https://www.spigotmc.org/resources/nunpcdestinations-create-living-npcs-1-8-3-1-11.13863/) to make my NPCs go to work in the morning and go home and night but when they go home players can still go into their homes and do quests so I was wondering if it's possible to make it once it's night or they go home the player can't get quests or talk to them until morning the next day.

**Comment by FlyingPikachu** [comment]
Unfortunately, we are not looking to natively integrate with any plugins at this time due to lack of manpower. I would suggest making a plugin request for a nuNPCDesintations-module on the Spigot forums. Thanks for your interest in Quests!
