### ISSUE TITLE
Quests spams on player join

### ISSUE THREAD

**Issue by AlphabetoPT** [Blackvein/Quests#476]
Hello my server is cb 1.7.9 r02 with all updated quests and dependencies and the issue is that it spams some errors when a player joins the server. No matter what player is, even if he never did a quest.

My Config is:
http://pastebin.com/3QmThY66

Error Log is:
http://pastebin.com/kKf8Q3qB

This is not causing any major problem i just love a clean console and this is my only error.
If you could point me to the right direction in order to fix it i would appreciate it very much.

Best regards,
Thanks in advance

**Comment by FlyingPikachu** [comment]
@AlphabetoPT If this is still an issue, please submit a new ticket including your Quests version. Thanks!
