### ISSUE TITLE
Totem Causes plugin to Fail

### ISSUE THREAD

**Issue by kobe686** [Blackvein/Quests#479]
When using the quest to deliver items to an npc, if you set the item as the "Totem of Undying", it causes the plugin to error out and then changes over to the cut blocks stage (even though there never was one) and then no-matter what you type it restates the cut blocks menu again, even trying to follow along with it.

**Comment by FlyingPikachu** [comment]
@kobe686 You're gonna have to provide the error you speak of and your Quests version if the error does not include it.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
