### ISSUE TITLE
Download Link broken

### ISSUE THREAD

**Issue by SpaceduckLP** [Blackvein/Quests#486]
The link on the spigot site is down, pls update it as quickly as possible

can anyone upload the plugin and send the link? I need it...

**Comment by FlyingPikachu** [comment]
https://dl.dropboxusercontent.com/u/72509980/Quests-2.7.6.jar

@SpaceduckLP Thanks for the report! Investigating the issue.

**Comment by SpaceduckLP** [comment]
@FlyingPikachu thank you!

**Comment by FlyingPikachu** [comment]
Resolved
