### ISSUE TITLE
Quest NULL

### ISSUE THREAD

**Issue by KyoTGD** [Blackvein/Quests#487]
When I use the plugin in my server and do /quests I get:
Quests NULL
Quests NULL
Quests NULL
So on....

I am using Spigot 1.11.2. I tried running it on 1.11 but it gave the same error. Can someone explain to me what's wrong and how to fix it?

**Comment by FlyingPikachu** [comment]
I believe you are either using an older version of Quests or do not have Vault installed. If this is not the case, please post your Quests and Vault version and I will reopen the issue. Thanks!
