### ISSUE TITLE
REDO-DELAY BROKEN!! Players can cheat reward items!

### ISSUE THREAD

**Issue by ScuroK** [Blackvein/Quests#496]
Version:
 Build #120 (05.02.2017 20:19:07)

Problem:
If a player completes a quest and relog (leave and join again) to the server he can do the quest again!
This enables them to chat rewards!

**Comment by MegaNarwhal** [comment]
Any progress on this?

**Comment by Xoezer** [comment]
^Bump

**Comment by FlyingPikachu** [comment]
Duplicate of #329
