### ISSUE TITLE
DOWNLOADLINK NOT WORK

### ISSUE THREAD

**Issue by zeratulh** [Blackvein/Quests#501]
Hello, the downloadlinks doesnt work pls fix!

**Comment by Loivado** [comment]
Hi, 
your issue doesn't really help to identify your problem... I don't even know which download link you are referring too. If you mean the Jenkins, I have no problem downloading the 120th build.

For downloading from Jenkins: 
- Go to: [ci.ac3-servers.eu/job/Quests](http://ci.ac3-servers.eu/job/Quests/)
- Click the build you want on the left side. 
- Click the .jar (for #120 its "Quests-2.7.6.jar")

**Comment by FlyingPikachu** [comment]
Just downloaded with no issues. If this is still a problem, please open a new ticket. Thanks!
