### ISSUE TITLE
How can I do this?

### ISSUE THREAD

**Issue by Ajka2** [Blackvein/Quests#503]
Hey! (: First of all, your plugin is **awesome**.
But I'm trying to do something, and I don't know if I actually can.
What I want to do is that one player goes and talks to one of the NPC's. He asks the player to go to talk to another NPC so he can give him something, so the player comes back with the first NPC to give him that thing.
Is there any way to do it?

Thank you!

**Comment by Loivado** [comment]
Hi, 
it's easy with several quests but I don't think you can just do this with Stages as you want to **reward** the player for talking to another NPC.
- Create Quest 1 for NPC 1.
- Stage 1 of Quest 1: Talk to NPC 2.
- Set your Quest Item Reward. (E.g. an Item which has a Display Name and Lore so it can't be crafted or found by players)
- Create Quest 2 for NPC 2.
- Stage 1 of Quest 2: Deliver Items to NPC 1 (you can add items simply ingame via the menu, also setting display name and lore ingame is possible)

I don't really think that is an Issue here. It's more a use case, I would recommend you to read some of the wiki before setting up software issues. [Wiki - also has all Infos about the Stages](https://github.com/Blackvein/Quests/wiki/Configuration)

**Comment by FlyingPikachu** [comment]
@Loivado Thanks!
