### ISSUE TITLE
Block variation does not seem to be working

### ISSUE THREAD

**Issue by magicbegins** [Blackvein/Quests#505]
Hi! First off, I absolutely love this plugin. It gives my users a great deal of achievement and a way to reward their efforts.

Problem is, I can't seem to successfully create a stage that uses Break Block, Damage Block, Place Block, Use Block or Cut Block. Setting the block name to **Dirt** always results in the quest requiring **Coarse Dirt** instead, and setting the block name to **Stone** results in the quest requiring **Granite** instead.

In my quests.yml, the `break-block-names:` is appropriately set to - **STONE**, but the quest still asks for **Granite**.

Setting the block name to **Stone** and mining **Granite** actually **allows me** to complete this quest. 

Any way around this?

Many thanks!

**Comment by FlyingPikachu** [comment]
@magicbegins Did you set the durability as well? If you're uncertain, post that portion from your quests.yml and perhaps someone here can help you.

**Comment by FlyingPikachu** [comment]
Closing due to lack of response from OP.
