### ISSUE TITLE
One more

### ISSUE THREAD

**Issue by Ajka2** [Blackvein/Quests#506]
Sorry, but I have to ask you something else. 
Is there a way to hide some of the quests until others are completed?

**Comment by Loivado** [comment]
Hi, 
yes you can do this.
Use the Requirement "Quests". The Ingame texts will help you when creating/editing your quest. You simply have to put the name of the Quest which is required to start the next one.
Other requirement options you can find on the wiki page: https://github.com/Blackvein/Quests/wiki/Configuration

**Comment by FlyingPikachu** [comment]
@Loivado Thanks!
