### ISSUE TITLE
Compatibility with MythicMobs over Module ERROR

### ISSUE THREAD

**Issue by muckmuck** [Blackvein/Quests#507]
Through the last update of MythicMobs, were the owner updated his package structure your plugin Quests didn't support this yet. So I rewrite the module but actually I think there is a bug in the CustomObjectives. So the modules cannot be loaded or executed.
Pls fix this soon.

**Comment by FlyingPikachu** [comment]
That module is maintained by the makers of MythicMobs. Please inform them. Thanks!
