### ISSUE TITLE
Jenkins Links Failing to Download

### ISSUE THREAD

**Issue by jjhhgg100123** [Blackvein/Quests#508]
Hello, I've tried multiple browsers and the Jenkins links (#120 and #119) seem to be broken. On Firefox it either says Failed to download, unknown time left, or it gets to 3%~ and stops. Other people seem to be having this issue, as seen the in the spigot discussion page. Hopefully this can be resolved. Thanks!

Edit: I've also tried using VPN-ing to a Canadian server (I'm on the East Coast) and it still fails.

**Comment by FlyingPikachu** [comment]
Just downloaded with no issues. If this is still a problem, please open a new ticket. Thanks!
