### ISSUE TITLE
Multiple Issues with Quests 2.7.6 (Download Solution)

### ISSUE THREAD

**Issue by Reversiya** [Blackvein/Quests#509]
These are some issues that I have been facing, and a solutions.

The download issue. There is a download issue when downloading Quests 2.7.6 off of jenkins. The download will freeze on Chrome at around 10-25%. Fix at bottom.

The loading issue. Quests 2.7.6 will not load on paperspigot 1.8.8 and other versions of 1.8 from what I know. There are no solutions to this as of yet. I would recommend using an older version. :/

Fix -----

What fixed this for me - Cancelling the download on the downloads page of chrome, re-downloading. The second time it will say preparing for around 2-3 minutes and instantly be finished downloading.

**Comment by FlyingPikachu** [comment]
Just downloaded with no issues. If this is still a problem, please open a new ticket. Thanks!
