### ISSUE TITLE
Some break-block-names not working

### ISSUE THREAD

**Issue by vilgrar** [Blackvein/Quests#515]
Hi,

I tried setting up a quest to break acacia logs, but the plugin refuses to accept log2 as a break-block-name. I noticed a similar problem with other names, such as planks and stained_hardened_clay. I'm using Quests 2.7.6, the release version at Spigotmc.

This is the part of the quest that simply refuses to work:

       '1':
          break-block-names:
          - log2
          break-block-amounts:
          - 56
          break-block-durability:
          - 0

**Comment by FlyingPikachu** [comment]
@vilgrar because "log2" is not the name of any known block. I believe you simply want "log" for break-block-name and "2" for break-block-durability.

**Comment by vilgrar** [comment]
According to [http://minecraft-ids.grahamedgecombe.com/], the name of Acacia Wood and Dark Oak Wood is log2? Those are the ones I can't use.

**Comment by FlyingPikachu** [comment]
@vilgrar My mistake, you are correct. Try "log_2" with the underscore and let me know. From the [Item Formatting page of the Wiki](https://github.com/Blackvein/Quests/wiki/Item-Formatting), it's recommended you use this for material names:

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by vilgrar** [comment]
I can't believe it was that easy. Thanks for the link, it's working now! =)
