### ISSUE TITLE
Reload? Issues with quests {being removed}

### ISSUE THREAD

**Issue by Saelman** [Blackvein/Quests#516]
18.05 01:59:35 [Server] ERROR [Quests] Stone Miner inside quests: Requirement for Quest Mob Hunter is not a valid Quest name!
18.05 01:59:35 [Server] ERROR [Quests] Make sure you are using the Quest name: value, and not the block name.
18.05 01:59:35 [Server] ERROR [Quests] Stone Miner inside quests: Requirement for Quest Catch Fish is not a valid Quest name!
18.05 01:59:35 [Server] ERROR [Quests] Make sure you are using the Quest name: value, and not the block name.
18.05 01:59:35 [Server] ERROR [Quests] Stage 1 of Quest Starter is missing break-block-durability:
18.05 01:59:35 [Server] ERROR [Quests] Wither Skeleton inside mobs-to-kill: inside Stage 1 of Quest Kill Asher is not a valid mob name!

the quest does show up after a reload. i edited the asher 1 (18.05 01:59:35 [Server] ERROR [Quests] Wither Skeleton inside mobs-to-kill: inside Stage 1 of Quest Kill Asher is not a valid mob name!) and it no longer is able to be edited or deleted. i removed the delay so they can only do i 1 time. i was able to create and reload it and it worked. edited it and it broke.

**Comment by FlyingPikachu** [comment]
@Saelman You will want to post the relevant quest from your quests.yml if you are still seeking assistance. Thanks!
