### ISSUE TITLE
break-block quests are duplicating after relog

### ISSUE THREAD

**Issue by frendlyZ** [Blackvein/Quests#517]
Hello,

I have a big problem, when player takes quest, where he has to break or place blocks and he disconnect, it duplicates. So he doesn't have to mine or place 64 stones once, but twice and the duplicated quest doesn't count, so it's not possible to complete the quest.

**Comment by MegaNarwhal** [comment]
I believe I have the same or a similar issue. When a player relogs, the quest journal shows progress for block break requirements as 0, but this is what their data file looks like:
```currentQuests:
- Catch Fish
- Lawnmower
currentStages:
- 0
- 0
quest-points: 2
questData:
  Catch Fish:
    fish-caught: 2
    chat-triggers:
    - rod
  Lawnmower:
    blocks-broken-names:
    - LONG_GRASS
    - LONG_GRASS
    - LONG_GRASS
    - LONG_GRASS
    - LONG_GRASS
    - LONG_GRASS
    blocks-broken-amounts:
    - 0
    - 37
    - 37
    - 37
    - 37
    - 37
    blocks-broken-durability:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
```

**Comment by frendlyZ** [comment]
Did you somehow fixed it?

**Comment by LeZalox** [comment]
Same problem on every version of Quests I run.

**Comment by FlyingPikachu** [comment]
@frendlyZ Quests version?

**Comment by frendlyZ** [comment]
2.7.*

**Comment by FlyingPikachu** [comment]
@frendlyZ The asterisk is not sufficient. Please post the entire version number.

**Comment by frendlyZ** [comment]
It does on every 2.7 version, I have 2.7.6 now
