### ISSUE TITLE
Question: Is it possible to run newer Quests Plugin with a older Citizens Plugin

### ISSUE THREAD

**Issue by Karlos96** [Blackvein/Quests#524]
My question is if it is possible to get a 1.7.10 version which work with the Citizens Version of 1.4.7 without spamming the console?
We running currently a 1.4.7 Modpack with an 1.7.10 Bukkit API.

greetings

karlos96

**Comment by Karlos96** [comment]
Wrong Project Lel

**Comment by Karlos96** [comment]
Reopened

**Comment by FlyingPikachu** [comment]
Current version of Quests (2.7.6) should be compatible with all Bukkit builds above 1.7.2. If this is not the case, open a new issue with a complete startup log. Keep in mind that modpacks are not officially supported by Quests, however.
