### ISSUE TITLE
Works with 1.11.2 but vault not compatible?

### ISSUE THREAD

**Issue by QueenKisaki** [Blackvein/Quests#525]
Not sure but here's the error: https://pastebin.com/08Xj83ff

**Comment by FlyingPikachu** [comment]
@QueenKisaki As your error indicates, you are using an incompatible version of Vault and should update.

If you update and the problem persists, please post the version number of the new Vault installation. Thanks!

**Comment by QueenKisaki** [comment]
Oh I found the update, thank you!
