### ISSUE TITLE
Can;t seem to save a quest?

### ISSUE THREAD

**Issue by Ironic8b498** [Blackvein/Quests#527]
I'm running Quest 2.7.6, on Spigot 1.11.2 and I have done this about ten times and not one saved if I told it to save. What am I doing wrong?

**Comment by FlyingPikachu** [comment]
@Ironic8b498 Unless you have a console error or can list/show the steps you took, I'm afraid there's not much to go off of.

**Comment by Ironic8b498** [comment]
that's my problem if there was an error in the logs or in chat , I could most likely figure it out. Since I'm not getting any errors. What are the most common errors besides user error.

**Comment by Ironic8b498** [comment]
Must of forgot to delete the quest folder on fail of load in 1.12, seems to work now

**Comment by FlyingPikachu** [comment]
Glad you've worked it out! Updating to the latest dev build may improve compatibility with 1.12

**Comment by Ironic8b498** [comment]
right now I'm setting up in 1.11.2 then updating to 1.12 will get dev build then if needed
