### ISSUE TITLE
Quests 2.8.0 Not load at start

### ISSUE THREAD

**Issue by Sprungente** [Blackvein/Quests#529]
Hey Pikachu ❤️ 

https://pastebin.com/iura0rbH

This server is running CraftBukkit version git-Spigot-cd6ba67-a7d074c (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by Sprungente** [comment]
Reopen

Isnt' fixed with the newest devbuild
i delete the quests ordner and try it and it hasn't help.

Same error, same spigotversion.

**Comment by FlyingPikachu** [comment]
I did fix this in the last commit (you can see I [changed the version to 2.8.1](76ff8972b6846e41a877ca6e53a4a862cb3e086f)), but Jenkins compiled 2.8.0 again... very odd. I've just made a small change and pushed it, to see if this was a fluke. If not, I'll just compile the it myself and release 2.8.1 on Spigot later today.

**Comment by Sprungente** [comment]
@FlyingPikachu  Unfortunately it isnt fixed. Same error and all commands put out "NULL"

**Comment by Sprungente** [comment]
I created a empty data.yml und put it in the Jar. It has fixed.

I don't know why your data.yml not in the Jar maybe someone is going wrong.

**Comment by FlyingPikachu** [comment]
Fixed in #532
