### ISSUE TITLE
"NULL" problem

### ISSUE THREAD

**Issue by TheKgB2015** [Blackvein/Quests#531]
Hi!
The 1.12 version of your plugin doesn't work. It says Null for everything:
![quest](https://user-images.githubusercontent.com/11576032/27259900-fa0d5458-541d-11e7-9ffa-4f1e415023f2.png)

**Comment by Sprungente** [comment]
A temporary fix is, when you create and put an empty data.yml in the jar.

**Comment by TheKgB2015** [comment]
Still doesn't work.

**Comment by TheKgB2015** [comment]
Thanks, it works!

2017.06.18. 12:39 ezt írta ("Sprungente" <notifications@github.com>):
