### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Curtis73** [Blackvein/Quests#547]
Hey there,
Sorry to bother you - though my console is being spammed with:

> [Tue, 3. Oct 2017 16:59:55 BST WARN] [Quests] Quester data for UUID "a9a8e513-d178-403d-85cb-b640ba7b09d3" not stored. Attempting manual data retrieval...
> [Tue, 3. Oct 2017 16:59:55 BST INFO] [Quests] Quester not found for UUID "a9a8e513-d178-403d-85cb-b640ba7b09d3". Consider adding them to the Quester blacklist.
> [Tue, 3. Oct 2017 16:59:55 BST WARN] [Quests] Quester data for UUID "c46f05d5-d12f-4372-bf43-c169fdf87a8c" not stored. Attempting manual data retrieval...
> [Tue, 3. Oct 2017 16:59:55 BST INFO] [Quests] Quester not found for UUID "c46f05d5-d12f-4372-bf43-c169fdf87a8c". Consider adding them to the Quester blacklist.
> [Tue, 3. Oct 2017 16:59:55 BST WARN] [Quests] Quester data for UUID "e277d93a-9e17-4f07-aadd-f2be7f376a2a" not stored. Attempting manual data retrieval...
> [Tue, 3. Oct 2017 16:59:55 BST INFO] [Quests] Quester not found for UUID "e277d93a-9e17-4f07-aadd-f2be7f376a2a". Consider adding them to the Quester blacklist.

Whenever I add the UUIDs to the blacklist, it goes away, but comes back with some different UUIDs after a couple of hours, though when I try to add these UUIDs, it blacklists me - though my UUID isn't anything like the two above.

Does anyone have any pointers?
Thanks in advance!

**Comment by Swede37** [comment]
I'm getting that too.  I started off by blacklisting the UUID as suggested - and that simply left my admin with no Quests permissions.
Now, I'm seeing a different UUID, and upon looking it up, I find its a player online who isn't even trying to do a quest.

I'm really hoping for a solution, the amount of spam this creates in console makes it unusable.

**Comment by Sprungente** [comment]
https://github.com/FlyingPikachu/Quests

Here it' doesnt have support
